### ISSUE TITLE
Hive - Error Loading Data

### ISSUE THREAD

**Issue by ArterialMonkey** [flick116/MMM-Hive#2]
Hey,

Hope someone can assist.  New to this so bear with me!

I have installed the hive module, (i believe) I've configured this correctly (as i just want to view it) via the mirror.

When running MagicMirror2 i receive (displayed on screen): Hive - Error Loading Data.

Any suggestions as to where i am going wrong?  This is the last part of the creation of my mirror and just want to nail it.

Thanks

**Comment by maccy99** [comment]
Same here - cant seem to figure it out at all!!!

**Comment by ArterialMonkey** [comment]
And that’s the trick....... left it alone for a day (switched off), booted up and was presented with this!

[image1.png]

Not a great photo; but for no reason it’s now half working!

Go figure!!

Any assistance in getting the other half working would still be appreciated!

Have a good one!


Sent from my iPhone

On 7 Mar 2018, at 10:48, maccy99 <notifications@github.com<mailto:notifications@github.com>> wrote:


Same here - cant seem to figure it out at all!!!

**Comment by ArterialMonkey** [comment]
![c560c5e2-f2e0-46b4-a191-a1323166ac76](https://user-images.githubusercontent.com/37015211/37090821-c4f8d522-21fd-11e8-9de1-4c51ada413cd.png)

**Comment by maccy99** [comment]
Hi, i got to that part by changing outsideUrl from https to http but the problem is now half of it is working is hive/britishgas have changed their api address for insideUrl for security reasons and the original one here :- https://api-prod.bgchprod.info/Omnia does not work just returns error all the time... hope someone figures this out.....

**Comment by daymo87** [comment]
Anyone ever sort out the missing inside temperature issue??

**Comment by SimonJHudson** [comment]
Can anyone share their config file. I can't get it to work with the example provided. It looks to me like there are a couple of format errors - single rather than double quotes around the dummy postcode and an extra comma after the penultimate brace
		{
			module: "MMM-Hive",
			header: "Hive",
			position: "top_right",
			config: {
				temperatureSuffix: "°C",
				username: "hive@hive.com",
				password: "password",
				postcode: 'P0STC0D3',
				showNext: true,
			},
		},

**Comment by flick116** [comment]
It should all be working fine now - but any issues, let me know.

In regards to the config, that matches my config pretty much exact and it's working fine for me - are you still having issues?
